/* GENERATED by scripts/generate-tokens.mjs from icons/*.svg. Do not edit. */

export const ICONS = Object.freeze({
  "alert": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7.5V12.5\"/><path d=\"M12 16.5V16.5\"/>",
  }),
  "check": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<circle cx=\"12\" cy=\"12\" r=\"9\"/><polyline points=\"8 12.5 11 15.5 16 9\"/>",
  }),
  "cross": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M9 9L15 15M15 9L9 15\"/>",
  }),
  "grid": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M3 9H21M3 15H21M9 3V21M15 3V21\"/>",
  }),
  "monitor": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\"/><path d=\"M8 20H16M12 16V20\"/>",
  }),
  "moon": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<path d=\"M12 3A6.5 6.5 0 0 0 21 12A9 9 0 1 1 12 3Z\"/>",
  }),
  "package": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<path d=\"M12 3L20 7.5V16.5L12 21L4 16.5V7.5Z\"/><path d=\"M4 7.5L12 12L20 7.5M12 12V21\"/>",
  }),
  "refresh": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<path d=\"M18.06 9.5A7 7 0 1 1 12 6\"/><polyline points=\"9 3 12 6 9 9\"/>",
  }),
  "sun": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<circle cx=\"12\" cy=\"12\" r=\"3.5\"/><path d=\"M12 2.5V5M12 19V21.5M2.5 12H5M19 12H21.5\"/><path d=\"M5.28 5.28L7.05 7.05M16.95 16.95L18.72 18.72M5.28 18.72L7.05 16.95M16.95 7.05L18.72 5.28\"/>",
  }),
  "users": Object.freeze({
    attrs: Object.freeze({"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 24 24","width":"24","height":"24","fill":"none","stroke":"currentColor","stroke-width":"2","stroke-linecap":"round","stroke-linejoin":"round"}),
    body: "<circle cx=\"9\" cy=\"8\" r=\"3.5\"/><path d=\"M3 20A6 6 0 0 1 15 20\"/><path d=\"M15.5 4.7A3.5 3.5 0 0 1 15.5 11.3\"/><path d=\"M18 14.5A5.5 5.5 0 0 1 21 20\"/>",
  }),
});
