// Carried forward from Lesson 3: the modular type scale.
// 16px base, ratio 1.25, seven roles on seven consecutive steps.

export const BASE_PX = 16;
export const TYPE_RATIO = 1.25;
export const BASELINE_PX = 4;
export const MIN_LEGIBLE_PX = 12;

/** @type {readonly { role: string, step: number, weight: number }[]} */
export const TEXT_ROLES = Object.freeze([
  { role: "caption", step: -1, weight: 400 },
  { role: "body", step: 0, weight: 400 },
  { role: "subheading", step: 1, weight: 600 },
  { role: "heading", step: 2, weight: 600 },
  { role: "title", step: 3, weight: 650 },
  { role: "headline", step: 4, weight: 700 },
  { role: "display", step: 5, weight: 700 },
]);

/**
 * @param {number} step
 * @param {{ base?: number, ratio?: number }} [opts]
 */
export function modularScale(step, { base = BASE_PX, ratio = TYPE_RATIO } = {}) {
  return base * ratio ** step;
}

/** Size x 1.2 + 4px, rounded up to the 4px rhythm. @param {number} sizePx */
export function lineHeightFor(sizePx) {
  return Math.ceil((sizePx * 1.2 + 4) / BASELINE_PX) * BASELINE_PX;
}

/** @param {{ base?: number, ratio?: number }} [opts] */
export function buildScale(opts = {}) {
  return TEXT_ROLES.map(({ role, step, weight }) => {
    const sizePx = modularScale(step, opts);
    return { role, step, weight, sizePx, lineHeightPx: lineHeightFor(sizePx) };
  });
}

export const typeScale = Object.freeze(buildScale());

/** @param {number} px */
const rem = (px) => `${+(px / BASE_PX).toFixed(4)}rem`;

/** The stylesheet scripts/generate-tokens.mjs writes to typography.css. */
export function typographyCss() {
  const vars = typeScale
    .map(
      (s) =>
        `  --pulse-font-size-${s.role}: ${rem(s.sizePx)};\n` +
        `  --pulse-line-height-${s.role}: ${rem(s.lineHeightPx)};\n` +
        `  --pulse-font-weight-${s.role}: ${s.weight};`,
    )
    .join("\n");
  const classes = typeScale
    .map(
      (s) =>
        `.pulse-text-${s.role} {\n` +
        `  font-size: var(--pulse-font-size-${s.role});\n` +
        `  line-height: var(--pulse-line-height-${s.role});\n` +
        `  font-weight: var(--pulse-font-weight-${s.role});\n}`,
    )
    .join("\n\n");
  return `/* GENERATED by scripts/generate-tokens.mjs from tokens/typography.js. Do not edit. */\n\n:root {\n${vars}\n}\n\n${classes}\n`;
}
