// Writes the generated files from their sources:
//   typography.js -> typography.css (Lesson 3)
//   colors.js     -> colors.css     (Lesson 4)
//   spacing.js    -> spacing.css    (Lesson 5)
//   icons/*.svg   -> icons/icons.js (Lesson 6)
// `--check` fails if any generated file has drifted from its source.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { ROOT } from "./workspace.mjs";

const SRC = `${ROOT}packages/design-system/src/`;
const DIR = `${SRC}tokens/`;
export const ICON_DIR = `${SRC}icons/`;
const OUTPUTS = /** @type {const} */ ([
  ["typography.css", "typography.js", "typographyCss"],
  ["colors.css", "colors.js", "colorsCss"],
  ["spacing.css", "spacing.js", "spacingCss"],
]);

/** Fresh import each time, so a long-running dev server sees edits. @param {string} file */
const fresh = (file) => import(`${pathToFileURL(file).href}?t=${Date.now()}`);

/** The icon files, by name, sorted. */
export function iconFiles() {
  return readdirSync(ICON_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort()
    .map((f) => ({ name: f.slice(0, -4), file: ICON_DIR + f }));
}

/** icons.js: every .svg file's root attributes and shapes, as data. */
async function iconsModule() {
  const { checkIcon, shapeMarkup } = await fresh(`${ICON_DIR}convention.js`);
  const entries = iconFiles().map(({ name, file }) => {
    const { attrs, shapes } = checkIcon(readFileSync(file, "utf-8"));
    return `  ${JSON.stringify(name)}: Object.freeze({\n    attrs: Object.freeze(${JSON.stringify(attrs)}),\n    body: ${JSON.stringify(shapes.map(shapeMarkup).join(""))},\n  }),`;
  });
  return `/* GENERATED by scripts/generate-tokens.mjs from icons/*.svg. Do not edit. */\n\nexport const ICONS = Object.freeze({\n${entries.join("\n")}\n});\n`;
}

/** @returns {Promise<Record<string, string>>} path (relative to src/) -> content */
async function render() {
  /** @type {Record<string, string>} */
  const out = {};
  for (const [css, js, fn] of OUTPUTS) out[`tokens/${css}`] = (await fresh(DIR + js))[fn]();
  out["icons/icons.js"] = await iconsModule();
  return out;
}

export async function generate() {
  const out = await render();
  for (const [file, text] of Object.entries(out)) writeFileSync(SRC + file, text);
  return Object.keys(out);
}

export async function staleFiles() {
  const out = await render();
  return Object.entries(out)
    .filter(([file, text]) => {
      try {
        return readFileSync(SRC + file, "utf-8") !== text;
      } catch {
        return true;
      }
    })
    .map(([file]) => file);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes("--check")) {
    const stale = await staleFiles();
    if (stale.length) {
      console.error(`FAIL: ${stale.join(", ")} out of date with their sources. Run pnpm tokens.`);
      process.exit(1);
    }
    console.log("OK: typography.css, colors.css, spacing.css and icons.js match their sources.");
  } else {
    await generate();
    console.log("Wrote typography.css, colors.css, spacing.css and icons.js.");
  }
}
