// Lesson 5: the spacing scale and the layout grid.
//
// One base unit, 8px. Every space in the UI is a whole number of units, and
// a step is named by how many units it holds: space-3 is 3 x 8 = 24px.
// Layout roles (gutter, page margin, panel padding) point at a step, the same
// way colour roles point at a palette entry in colors.js.

export const BASE_UNIT_PX = 8;

/** The multiples the scale offers. The jumps widen as spaces get bigger. */
export const SPACE_STEPS = Object.freeze([1, 2, 3, 4, 6, 8]);

/** @typedef {{ name: string, multiple: number, px: number }} SpaceStep */

/** @type {readonly SpaceStep[]} */
export const spaceScale = Object.freeze(
  SPACE_STEPS.map((multiple) => Object.freeze({ name: `space-${multiple}`, multiple, px: multiple * BASE_UNIT_PX })),
);

/** The board's grid: 12 equal columns, one column below this width. */
export const GRID_COLUMNS = 12;
export const NARROW_BELOW_PX = 960;

/**
 * What each layout space is FOR, as a step multiple, on wide and narrow
 * screens. Components use var(--pulse-layout-<role>) or var(--pulse-space-N).
 * @type {Readonly<Record<string, { wide: number, narrow: number }>>}
 */
export const layoutRoles = Object.freeze({
  gutter: { wide: 3, narrow: 2 },
  "page-margin": { wide: 4, narrow: 2 },
  "panel-padding": { wide: 3, narrow: 2 },
});

/** @param {number} multiple */
export const spaceVar = (multiple) => `--pulse-space-${multiple}`;

/** Sub-pixel slack for measured lengths (layout rounding), never a whole pixel. */
const TOLERANCE_PX = 0.05;

/** The scale step a length equals, or null. @param {number} px */
export function stepFor(px) {
  return spaceScale.find((s) => Math.abs(s.px - Math.abs(px)) <= TOLERANCE_PX) ?? null;
}

/**
 * Classify one measured length against the grid:
 *   "step"     equals a scale step (24px is space-3)
 *   "multiple" a whole number of units the scale doesn't name (40px is 5 x 8)
 *   "off-grid" anything else (16.6px, 12.8px, 3px)
 * @param {number} px
 * @returns {"step" | "multiple" | "off-grid"}
 */
export function classifyLength(px, base = BASE_UNIT_PX) {
  if (stepFor(px)) return "step";
  const units = Math.abs(px) / base;
  return Math.abs(units - Math.round(units)) * base <= TOLERANCE_PX ? "multiple" : "off-grid";
}

/** @param {"wide" | "narrow"} size @param {string} indent */
function roleDeclarations(size, indent) {
  return Object.entries(layoutRoles)
    .map(([role, def]) => `${indent}--pulse-layout-${role}: var(${spaceVar(def[size])});`)
    .join("\n");
}

/** The stylesheet scripts/generate-tokens.mjs writes to spacing.css. */
export function spacingCss() {
  const steps = spaceScale.map((s) => `  ${spaceVar(s.multiple)}: ${s.px}px;`).join("\n");
  const spans = Array.from({ length: GRID_COLUMNS }, (_, i) => `.pulse-span-${i + 1} { grid-column: span ${i + 1}; }`).join("\n");
  const stacks = spaceScale
    .map((s) => `.pulse-stack-${s.multiple} { display: flex; flex-direction: column; gap: var(${spaceVar(s.multiple)}); }`)
    .join("\n");
  const clusters = spaceScale
    .map((s) => `.pulse-cluster-${s.multiple} { display: flex; flex-wrap: wrap; align-items: center; gap: var(${spaceVar(s.multiple)}); }`)
    .join("\n");
  const narrow = `(max-width: ${NARROW_BELOW_PX - 0.02}px)`;
  return `/* GENERATED by scripts/generate-tokens.mjs from tokens/spacing.js. Do not edit. */

:root {
  --pulse-space-unit: ${BASE_UNIT_PX}px;
${steps}
  --pulse-grid-columns: ${GRID_COLUMNS};
${roleDeclarations("wide", "  ")}
}

@media ${narrow} {
  :root {
${roleDeclarations("narrow", "    ")}
  }
}

/* The grid: equal columns, gutters from the layout role. */
.pulse-grid {
  display: grid;
  grid-template-columns: repeat(var(--pulse-grid-columns), minmax(0, 1fr));
  gap: var(--pulse-layout-gutter);
}
${spans}

@media ${narrow} {
  .pulse-grid > * { grid-column: 1 / -1; }
}

/* Stack: children in a column, one gap. Cluster: a wrapping row, one gap. */
${stacks}
${clusters}
`;
}
