// The Pulse type scale — Lesson 3.
//
// One ratio and one base size produce every text size on the platform:
//
//     size(step) = BASE_PX × RATIO ^ step
//
// Components never pick a size. They pick a ROLE (caption, body, ...), each
// role sits on one step of the scale, and the role's line-height and weight
// are derived here too. This file is the only place in the repo allowed to
// say how big text is; pulse/no-raw-font-size fails the lint everywhere else.

export const TYPE_RATIO = 1.25; // a "major third": each step is 25% bigger
export const BASE_PX = 16; // step 0 = the browser default, so 1rem = body text
export const BASELINE_PX = 4; // every line-height lands on a 4px rhythm
export const MIN_LEGIBLE_PX = 12; // no role may sit below this

export const FONT_FAMILY_SANS = '"Avenir Next", "Segoe UI Variable", "Segoe UI", system-ui, sans-serif';

// Seven roles, seven consecutive steps. Step -2 (10.24px) exists on the
// ratio but is deliberately NOT a role: it falls under MIN_LEGIBLE_PX.
export const TEXT_ROLES = Object.freeze([
  { role: "caption", step: -1, weight: 500, use: "table headers, metadata, badges" },
  { role: "body", step: 0, weight: 400, use: "table cells, paragraphs, controls" },
  { role: "subheading", step: 1, weight: 600, use: "panel and section headings" },
  { role: "heading", step: 2, weight: 600, use: "page section titles" },
  { role: "title", step: 3, weight: 700, use: "key figures, dashboard title" },
  { role: "headline", step: 4, weight: 700, use: "page headings" },
  { role: "display", step: 5, weight: 700, use: "one hero number per page, at most" },
]);

export function modularScale(step, { ratio = TYPE_RATIO, base = BASE_PX } = {}) {
  return base * ratio ** step;
}

// Leading tightens as text grows: size × 1.2 + 4px, rounded UP to the
// baseline. Small text gets ~1.5× its size, display text ~1.3×.
export function lineHeightFor(sizePx) {
  return Math.ceil((sizePx * 1.2 + 4) / BASELINE_PX) * BASELINE_PX;
}

// Build the full scale for any ratio — the Control Tower uses this to
// preview other ratios. Only the default ratio is ever shipped as CSS.
export function buildScale({ ratio = TYPE_RATIO, base = BASE_PX } = {}) {
  return TEXT_ROLES.map(({ role, step, weight, use }) => {
    const sizePx = modularScale(step, { ratio, base });
    const lineHeightPx = lineHeightFor(sizePx);
    return Object.freeze({
      role,
      step,
      weight,
      use,
      sizePx,
      lineHeightPx,
      sizeRem: sizePx / BASE_PX,
      lineHeightRem: lineHeightPx / BASE_PX,
    });
  });
}

export const typeScale = Object.freeze(buildScale());

export const fontSizeVar = (role) => `--pulse-font-size-${role}`;
export const lineHeightVar = (role) => `--pulse-line-height-${role}`;
export const fontWeightVar = (role) => `--pulse-font-weight-${role}`;

const trim = (n) => String(Number(n.toFixed(6)));

// The CSS custom properties (and one class per role) every stylesheet reads. Written to
// tokens/typography.css by `pnpm tokens`; `pnpm tokens --check` (part of
// `pnpm lint`) fails if the committed file has drifted from this function.
export function typographyCss(scale = typeScale) {
  const lines = [
    "/* GENERATED by scripts/generate-tokens.mjs from tokens/typography.js.",
    "   Do not edit by hand: change typography.js and run `pnpm tokens`. */",
    ":root {",
    `  --pulse-type-ratio: ${TYPE_RATIO};`,
    `  --pulse-font-family-sans: ${FONT_FAMILY_SANS};`,
  ];
  for (const s of scale) {
    lines.push(
      `  ${fontSizeVar(s.role)}: ${trim(s.sizeRem)}rem; /* step ${s.step}, ${trim(s.sizePx)}px */`,
      `  ${lineHeightVar(s.role)}: ${trim(s.lineHeightRem)}rem; /* ${s.lineHeightPx}px */`,
      `  ${fontWeightVar(s.role)}: ${s.weight};`
    );
  }
  lines.push("}", "");
  // One class per role, so markup can say "this is a caption" directly.
  for (const s of scale) {
    lines.push(
      `.pulse-text-${s.role} { font-size: var(${fontSizeVar(s.role)}); line-height: var(${lineHeightVar(s.role)}); font-weight: var(${fontWeightVar(s.role)}); }`
    );
  }
  lines.push("");
  return lines.join("\n");
}
